### PR TITLE
#125 fix

### PR DESCRIPTION
**Pull request by accesslubos**
This should fix the #125 issue

### CODE REVIEW

**Comment by bulkan** [comment]
cheers ! but the tests are failing now.

**Comment by accesslubos** [comment]
Why's that? One line changed in one function only and it's not even building properly?

**Comment by bulkan** [comment]
https://travis-ci.org/bulkan/robotframework-requests/jobs/151145721

**Comment by vkosuri** [comment]
Test are failing due to pip, pip 7 doesn't have --user-mirror option, you could remove that option in [tarvis.yml](https://github.com/bulkan/robotframework-requests/blob/master/.travis.yml#L8) file. Try to rebuild again, hope it will works.

``` Shell
$ python --version

Python 2.6.9

$ pip --version

pip 7.1.2 from /home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages (python 2.6)

0.29s$ pip install -r requirements.txt --use-mirrors

Usage:   

  pip install [options] <requirement specifier> [package-index-options] ...

  pip install [options] -r <requirements file> [package-index-options] ...

  pip install [options] [-e] <vcs project url> ...

  pip install [options] [-e] <local project path> ...

  pip install [options] <archive url/path> ...

no such option: --use-mirrors
```

**Comment by accesslubos** [comment]
Thanks dude, it's all green now. :)

**Pull request merged**
