### PR TITLE
slow behind corporate proxy

### PR DESCRIPTION
**Pull request by vkosuri**
This fix is related to https://github.com/bulkan/robotframework-requests/issues/116 and https://github.com/bulkan/robotframework-requests/issues/120

### CODE REVIEW

**Comment by vkosuri** [comment]
@bulkan any comments?

**Comment by bulkan** [comment]
@vkosuri tests are failing

**Comment by vkosuri** [comment]
@bulkan thanks, looking into failures

**Comment by vkosuri** [comment]
@bulkan busy in traveling, will fix failures by this week

**Comment by vkosuri** [comment]
@bulkan I appoligies i haven't get chance look into this issue, make sure i will do this ASAP

**Pull request closed without merging**
