### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by ineiros**
This pull request provides initial Python 3 compatibility.
All tests in tests/ pass on Python 2.7 and Python 3.5. 

Not all code paths have been checked meticulously, so it is possible that this breaks some untested cases in Python 2.

### CODE REVIEW

**Comment by vkosuri** [comment]
@bulkan If you try to merge this pull request, some of the related issues are with same subject

1. https://github.com/bulkan/robotframework-requests/pull/113
2. https://github.com/bulkan/robotframework-requests/pull/115
3. https://github.com/bulkan/robotframework-requests/pull/119

**Comment by ineiros** [comment]
Certainly the changes in compat.py can be put directly into RequestLibrary, and the imports can be changed into try-except so that they come before the PY3 definition. It is mostly an aesthetic choice: it keeps the import lists clean in actual code and confines the hairy changes in a single file that can be a helpful reference when handling compatibility in other projects.

**Comment by bulkan** [comment]
Hey @vkosuri I've added you as a collaborator to this project.   You can now merge these PR's.

**Comment by vkosuri** [comment]
Thank you @bulkan, i am merging this PR into master.

@ineiros thanks for this merge, cheers!!

**Pull request merged**
