### PR TITLE
Add protobuf

### PR DESCRIPTION
**Pull request by mmikirtumov**
It will be better to have ability to send requests using protobuf.

Only limitation that it requires to create dummy keyword to inject protobuf python modules

### CODE REVIEW

**Comment by vkosuri** [comment]
Great work 👍

**Comment by lucagiove** [comment]
Indeed a nice work but I'm not sure how this has been integrated.
I mean this library is intended mainly to wrap python requests and provide the core functionalities around HTTP request/response.

Protobuf is a quite specific serialization method, I wouldn't add a parameter to all keywords to manage them since 99% of the users won't even know what protobuf is.
Json are handled because a de facto standard and it is already managed by original requests library itself.

Maybe helper keywords to encode / decode protobuf to be passed as data in the requests would suite more the aim of the library.
Also logging could be included in those keyword, don't know we might discuss about it.

Moreover this quite big change without a single test cannot be merged imho.

**Comment by mmikirtumov** [comment]
Hi @lucagiove 

Thank you for your feedback.

Mostly I agree that this wonderful library create opportunity to wrap python requests and provide the core functionalities around HTTP request/response. Also using python request you can send and response protobuf and there is no restrictions. Protobuf just protocol and I think it will be better to support also this protocol. And a lot of new services start using this mechanism.

`Protobuf is a quite specific serialization method, I wouldn't add a parameter to all keywords to manage them since 99% of the users won't even know what protobuf is.` - As you can see there are two parameters. Or I you want to introduce something different? But I think it will be better to create some documentation how to use with protobuf. As I understand my changes should not break anything and it will continue work as it is.

`Maybe helper keywords to encode / decode protobuf to be passed as data in the requests would suite more the aim of the library.` - IMHO giving opportunity library to have this functionality will be better and easier to maintain existing projects, specially it will not break anything.

I can also add new tests and logging. 👍

**Comment by lucagiove** [comment]
Hi @mmikirtumov I see you working on this thanks!

> `Protobuf is a quite specific serialization method, I wouldn't add a parameter to all keywords to manage them since 99% of the users won't even know what protobuf is.` - As you can see there are two parameters. Or I you want to introduce something different? But I think it will be better to create some documentation how to use with protobuf. As I understand my changes should not break anything and it will continue work as it is.

I see you're not breaking anything that's good. By the way the methods signatures are quite changed with new 4 parameters that most of the time won't be used and that are not available to original requests  as well.

My point is that I'd like to keep the http methods as much stick as possible to original requests and the aim of handling HTTP protocol.
Otherwise tomorrow someone wants to handle Avro serialization and adds other parameters.

Do you think there would be alternatives?
Maybe you can create two keywords one to prepare data to be passed to the http method keywords and one to parse the response payload?
This would be a less impacting change that easily allow support for other data serialization in the future without spoiling the keyword signature.
I would approve a PR with a more conservative approach,

Thanks!
Luca

**Comment by mmikirtumov** [comment]
Hi Luca,

Thank you for your suggestion. 

I see your point that you don't want to increase library in this way and leave the keywords as simple as it is possible. 

In library there are also some parameters which can most of time won't use for some reasons. I thought that this approach will be much flexible and easier to use than additional keyword for only serialize and deserialize, because it will encapsulate all logic in one place and there is no need to add additional steps using keyword. If engineers try to use protobuf their should always introduce 2 additional keywords in their test cases. And also library gives us opportunity which parameters to send and which parameters to skip.

I will try to create different PR and maybe we can discuss the pros and cons of these two approaches. 👍 

Thanks!
Mikayel

**Comment by bulkan** [comment]
Hi all,

I agree with what @lucagiove wrote above;

> I mean this library is intended mainly to wrap python requests and provide the core functionalities around HTTP request/response.

What's the reasoning behind adding `protobuf` support to this library ? 

I would suggest creating a new keyword library instead.

**Comment by mmikirtumov** [comment]
Hi @bulkan ,

The idea is to enhance the library and also support build in `protobuf` protocol. 

I think we can encapsulate any http request response logic (in this case specific serialization protocol) in this library and give opportunity to other engineers use it quickly and in a easy way without additional efforts.

Why I thought that it will valuable for library: I found the following function in code `_format_data_according_to_header` which is actually do some additional thinks on top of request library based on header and protobuf is just another Content-Type

```
def _format_data_according_to_header(self, session, data, headers, protobuf_request_type, protobuf_response_class_type):
        # Merged headers are already case insensitive
        headers = self._merge_headers(session, headers)

        if data is not None and headers is not None and 'Content-Type' in headers and headers['Content-Type'].find("application/x-protobuf") != -1:
            return self._convert_data_to_protobuf(data, protobuf_request_type, protobuf_response_class_type)

        if data is not None and headers is not None and 'Content-Type' in headers and not self._is_json(data):
            if headers['Content-Type'].find("application/json") != -1:
                if not isinstance(data, types.GeneratorType):
                    data = json.dumps(data)
            elif headers['Content-Type'].find("application/x-www-form-urlencoded") != -1:
                data = self._utf8_urlencode(data)
        else:
            data = self._utf8_urlencode(data)

        return data
```

Thanks

**Comment by lucagiove** [comment]
Maybe we can think about creating a dynamic way to support different payload encoding/serialization just by changing the headers.
We could avoid multiple parameters and just guess how to prepare/parse the data for the response.
In this way the response object could have response.protobuf() just like json().
I would anyway start by creating a separate method/object to handle the data preparation/parse.

**Comment by bulkan** [comment]
As I don't use RF anymore I will leave it up to @lucagiove and @asyrjasalo to decide on if adding `protobuf` serialization support is a good idea.

**Comment by lucagiove** [comment]
For the moment this won't be included but I'm thinking about a plugin or similar way to provide api to encode/decode and log with custom payload not officially supported by requests this might be an interesting feature but at the moment in the lib roadmap there are more urgent changes to do.

**Pull request closed without merging**
