### PR TITLE
Python3 removes execfile, work around this by manually opening the fi…

### PR DESCRIPTION
**Pull request by bobdoah**
…le, reading, compiling and then execing the code this is for issue #109

### CODE REVIEW

**Comment by bulkan** [comment]
Thanks @bobdoah. Is this change backwards compatible with Python 2.x ?

**Comment by vkosuri** [comment]
I think tr‎avis executed on ``Python 2.6 and 2.7`` . It's time to add Python 3.0 intrapreter to this project.                                                                                                                                                                                                     Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Bulkan EvcimenSent: Friday 13 May 2016 04:58To: bulkan/robotframework-requestsReply To: bulkan/robotframework-requestsSubject: Re: [bulkan/robotframework-requests] Python3 removes execfile, work around this by manually opening the fi… (#110)‎Thanks @bobdoah. Is this change backwards compatible with Python 2.x ? 

—You are receiving this because you are subscribed to this thread.Reply to this email directly or view it on GitHub

**Comment by bobdoah** [comment]
Travis did execute on Python 2.6 and 2.7. I've installed it manually on python 2.7 too and run a sample test case, which was fine.

I suspect there are other Python3 issues, when I tried to execute a sample I got:

```bash
(robotframework-requests-python3) rowilliams@bateman:~/work/docker_playground$ robot sample.robot
[ ERROR ] Error in file '/home/rowilliams/work/docker_playground/sample.robot': Importing test library 'RequestsLibrary' failed: ImportError: No module named 'RequestsKeywords'
Traceback (most recent call last):
  File "/home/rowilliams/virtualEnvs/robotframework-requests-python3/lib/python3.4/site-packages/RequestsLibrary/__init__.py", line 1, in <module>
    from RequestsKeywords import RequestsKeywords
PYTHONPATH:
  /home/rowilliams/virtualEnvs/robotframework-requests-python3/bin
  /home/rowilliams/virtualEnvs/robotframework-requests-python3/lib/python3.4
  /home/rowilliams/virtualEnvs/robotframework-requests-python3/lib/python3.4/plat-x86_64-linux-gnu
  /home/rowilliams/virtualEnvs/robotframework-requests-python3/lib/python3.4/lib-dynload
  /usr/lib/python3.4
  /usr/lib/python3.4/plat-x86_64-linux-gnu
  /home/rowilliams/virtualEnvs/robotframework-requests-python3/lib/python3.4/site-packages
==============================================================================
Sample
==============================================================================
Get Requests                                                          | FAIL |
No keyword with name 'Create Session' found.
------------------------------------------------------------------------------
Sample                                                                | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /home/rowilliams/work/docker_playground/output.xml
Log:     /home/rowilliams/work/docker_playground/log.html
Report:  /home/rowilliams/work/docker_playground/report.html
(robotframework-requests-python3) rowilliams@bateman:~/work/docker_playground$
```

**Comment by vkosuri** [comment]
This pr https://github.com/bulkan/robotframework-requests/pull/130 has been merged into master, hence closing this issue.

**Comment by pradhan41** [comment]
Folks I am still getting the same error , has any one found solution for it 


C:\WINDOWS\system32>pip install -U robotframework-ride
Collecting robotframework-ride
  Using cached robotframework-ride-1.5.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c..."
        execfile(join(ROOT_DIR, 'src', 'robotide', 'version.py'))
    **# NameError: name 'execfile' is not defined**

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in

**Comment by bobdoah** [comment]
@pradhan41 That error is in a different library and it looks like you're out of luck as they won't support python 3 

https://github.com/robotframework/RIDE/issues/1587

**Comment by HelioGuilherme66** [comment]
@pradhan41 You can install RIDE from my fork with Python 3:
```
python3 -m pip install wxPython
python3 -m pip install  https://github.com/HelioGuilherme66/RIDE/archive/v1.7.1.zip 
```
Use with care, because there are crashes and bugs. See my Wiki at https://github.com/HelioGuilherme66/RIDE/.

**Comment by pradhan41** [comment]
I rolled back to 2.7 and was able to install seamlessly after that , looks like Python 3 doesn't yet support ride as yet . hopefully I don't run into any other issues down the road , thanks all

**Comment by sinnerag** [comment]
Thanks @HelioGuilherme66 
I was facing this issue. Your solution is good. Earlier i installed wxPython and was unable to install robotframework-ride. Tried just "pip install  https://github.com/HelioGuilherme66/RIDE/archive/v1.7.1.zip" and it worked like magic.

However when i try to launch ride using **ride.py** i get the following error

image

Am i missing something or is there something wrong. 
Any help would be appreciated.
Thank you.

**Comment by HelioGuilherme66** [comment]
@sinnerag Well, we should not be filling this closed Issue with comments.
You need to install  `pygments`
```
pip install Pygments
```

**Pull request closed without merging**
