### PR TITLE
Document cookie support

### PR DESCRIPTION
**Pull request by girone**
See #192

### CODE REVIEW

**Comment by bulkan** [comment]
@girone seems like this PR is now out of date

**Comment by girone** [comment]
I've rebased the PR onto latest upstream/master. However, Travis CI seems to fail. Locally, the tests succee. I need some time to figure out how to use Travis and maybe rerun and deflake the test build.

**Comment by bulkan** [comment]
@girone thank you. The Travis-CI failures are probably related to #200

**Comment by girone** [comment]
@bulkan is there a way to re-run the Travis build until it succeeds until #200 is solved?

**Comment by bulkan** [comment]
@girone I've ran the build on Travis a few times and its failing on that one test. I'm going to merge your changes and disable that test for the moment.

**Comment by girone** [comment]
Thanks for reviewing the PR!

**Pull request merged**
