### PR TITLE
logged requests operation information 

### PR DESCRIPTION
**Pull request by vkosuri**
logged requests operation information https://github.com/bulkan/robotframework-requests/issues/68

### CODE REVIEW

**Comment by vkosuri** [comment]
Could you please hold on i submitting another pull request

**Comment by vkosuri** [comment]
I have modified testcase accordingly, can i pull testcase also?

**Comment by vkosuri** [comment]
@bulkan Any updates on this? Please let me know any modification/suggestion on this PR?

**Comment by bulkan** [comment]
Awesome thanks for the PR

**Pull request merged**
