### PR TITLE
allow disable_warnings when max_retries=0

### PR DESCRIPTION
**Pull request by mstevenb**
Moves disable_warnings block outside `if max_retries > 0` condition to allow for disabling warnings when max_retries=0

### CODE REVIEW

**Comment by mstevenb** [comment]
My tests are expecting a failure response (HTTP 429) and I don't want the session/adapter to attempt any retries (thus setting `max_retries=0`).  I am then unable to disable warnings due to this condition.

**Comment by vkosuri** [comment]
@mstevenb thanks, @bulkan do you have any comments/suggestions on this PR

**Comment by vkosuri** [comment]
@mstevenb i apologize, i haven,t looked into thisnPR any updates

**Comment by mstevenb** [comment]
@vkosuri Let me know if there's anything I can do to help.  I have modified my local copy with the change, so no rush on my part.  Figured this would be the logical/expected behavior, so wanted to share the modification.

**Comment by vkosuri** [comment]
@mstevenb Cheers 👍

**Pull request merged**
