### PR TITLE
travis python 3

### PR DESCRIPTION
**Pull request by vkosuri**
Issue related to https://github.com/bulkan/robotframework-requests/pull/110

### CODE REVIEW

**Comment by vkosuri** [comment]
Reported a [issue ](https://github.com/robotframework/robotframework/issues/2372) waiting for response from robtframework

**Comment by bulkan** [comment]
Hey @vkosuri tests are failing for Python 2.7 & 3

**Comment by oleduc** [comment]
Hi @vkosuri I ran our hundreds of regression tests using this PR and some tests are now failing. I'm still investigating why.

**Comment by vkosuri** [comment]
Few things i observed are

``` Python
try: # Ptyhon 3
    from urllib import urlencode
except ImportError:
    from urllib.parse import urlencode

try:  # Python 3
     from http.client import HTTPConnection
 except ImportError:
     from httplib import HTTPConnection
```
and many ```Unicode``` errors are listed here https://github.com/robotframework/robotframework/issues/2372

**Comment by bulkan** [comment]
I don't think `unicode` exists in Python 3 as string literals are by default [unicode)(http://stackoverflow.com/questions/6812031/how-to-make-unicode-string-with-python3)

**Comment by magmax** [comment]
Sorry, I didn't realize this thread and started the migration on my own at #115 

It is working fine for me with python3, but now it fails with python2.

**Comment by vkosuri** [comment]
This PR https://github.com/bulkan/robotframework-requests/pull/130 has been merged into master hence closing this issue.

**Pull request closed without merging**
