### PR TITLE
Resolves #91, Verify parameter can accept String value

### LINKED ISSUE #91: Verify parameter should accept String value
Requests library allow to configure the CA bundle file or directory with certificates of trusted CAs with the `verify` parameter: http://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification

In the `_create_session` function, the `verify` parameter is converted to boolean: https://github.com/bulkan/robotframework-requests/blob/master/src/RequestsLibrary/RequestsKeywords.py#L129

I think we should allow `verify` parameter to be a String value to be able to configure CA bundle.

### PR DESCRIPTION
**Pull request by Mogztter**
I think we can add a test case with this cacert bundle: http://curl.haxx.se/ca/cacert.pem 
How do you run tests ?

Resolves #91

### CODE REVIEW

**Comment by bulkan** [comment]
The tests itself is written in Robot Framework test case files

`pybot -P src tests`

**Comment by vkosuri** [comment]
This PR failed due max retries reached on httpbin.org/get may be at that it wasn't responded, could you please try it again?

```
[ WARN ] host=httpbin.org uri: /get not responding, Retrying in 0.94 seconds ...

[ WARN ] host=httpbin.org uri: /get not responding, Retrying in 2.04 seconds ...

[ WARN ] host=httpbin.org uri: /get not responding, Retrying in 4.22 seconds ...

[ ERROR ] host=httpbin.org uri: /get not responding, Max. Retries reached quitting !!!

Get HTTPS & Verify Cert                                               | FAIL |
```

I tried just now it is working fine

``` Robot
TEST Get HTTPS & Verify Cert
Full Name: 	Requests Tests.Get HTTPS & Verify Cert
Tags: 	get
Start / End / Elapsed: 	20160203 17:56:52.442 / 20160203 17:56:53.591 / 00:00:01.149
Status: 	PASS (critical)
00:00:00.002 KEYWORD RequestsKeywords . Create Session httpbin, https://httpbin.org, verify=True
Documentation: 	

Create Session: create a HTTP session to a server
Start / End / Elapsed: 	20160203 17:56:52.442 / 20160203 17:56:52.444 / 00:00:00.002
17:56:52.443 	INFO 	Creating Session using : alias=httpbin, url=https://httpbin.org, headers={},                     cookies=None, auth=None, timeout=None, proxies=None, verify=True,                     debug=0 	
00:00:01.145 KEYWORD ${resp} = RequestsKeywords . Get httpbin, /get
Start / End / Elapsed: 	20160203 17:56:52.444 / 20160203 17:56:53.589 / 00:00:01.145
17:56:52.445 	INFO 	Starting new HTTPS connection (1): httpbin.org 	
17:56:53.588 	INFO 	Deprication Warning  Use Get Request in the future 	
17:56:53.589 	INFO 	C:\Python27\lib\site-packages\requests\packages\urllib3\util\ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning 	
17:56:53.589 	INFO 	${resp} = <Response [200]> 	
00:00:00.001 KEYWORD BuiltIn . Should Be Equal As Strings ${resp.status_code}, 200
Documentation: 	

Fails if objects are unequal after converting them to strings.
Start / End / Elapsed: 	20160203 17:56:53.589 / 20160203 17:56:53.590 / 00:00:00.001
17:56:53.590 	INFO 	Argument types are:
<type 'int'>
<type 'unicode'>
```

**Comment by Mogztter** [comment]
I have two errors when running the tests suite:

 * `Post Request With XML File` > `Dictionary does not contain key 'Authorization'.`
 * `Get HTTPS & Verify Cert` > `RetryException: host=httpbin.org uri: /get not responding`

NOTE: I'm behind a corporate proxy and when running tests suite on master:

 * `Post Request With XML File` > `Dictionary does not contain key 'Authorization'.`

**Comment by vkosuri** [comment]
@Mogztter could you please wait until this PR merges into master https://github.com/bulkan/robotframework-requests/pull/86 It seems to me @oleduc still working on this PR, after successful merge could you try it again?

**Comment by Mogztter** [comment]
@vkosuri Any updates on @oleduc work ? :smile:

**Comment by vkosuri** [comment]
@Mogztter @bulkan merged @oleduc changes into master could try again?

**Comment by Mogztter** [comment]
@vkosuri Done!

**Comment by bulkan** [comment]
Thanks @Mogztter

**Pull request merged**
