### PR TITLE
added new post data test

### PR DESCRIPTION
**Pull request by vkosuri**
https://github.com/bulkan/robotframework-requests/issues/131

### CODE REVIEW

**Comment by vkosuri** [comment]
@bulkan any comments on this PR?

**Comment by vkosuri** [comment]
@bulkan any suggestions?

**Comment by bulkan** [comment]
LGTM 👍

**Comment by vkosuri** [comment]
@bulkan can i merge this into master?

**Comment by bulkan** [comment]
Yes you can ! 

P.S: You don't need to ask me if you can merge to master. If the tests pass then go for it.

**Comment by vkosuri** [comment]
@bulkan the Libdoc wasn't updated with my changes, do i need to do anything after these merge?

**Comment by bulkan** [comment]
Do you mean that this page http://bulkan.github.io/robotframework-requests/ hasn't updated ?

If so, then you need to merge master into the `gh-pages` branch

**Comment by vkosuri** [comment]
@bulkan thank you, i merged master into gh-pages 50f78c85ca808779c1a0fdc417d5474dbb6720ac still i haven't seen doc updates http://bulkan.github.io/robotframework-requests/

**Comment by bulkan** [comment]
oh try copying `https://github.com/bulkan/robotframework-requests/blob/master/doc/RequestsLibrary.html` to `index.html`

**Comment by vkosuri** [comment]
@bulkan thanks, Here is the updated link http://bulkan.github.io/robotframework-requests/

**Pull request merged**
