### PR TITLE
fix log empty bug

### LINKED ISSUE #155: Post with data but display as '<empty>'  in the log file
There are many new users meet this trouble, actually they write the data arg in the Post Request but they see this in the log file :

> 20170325 22:41:11.193 :  INFO : Post Request using : alias=api, uri=/post, data=<empty>, headers=None, files=None, allow_redirects=True 

They are often wondering whether the data value posted with the request correctly or not. This doubt comes more strongly when the sever gives an error response.

I've read the source code, only when headers is not None and 'Content-Type' in headers, data value can be logged correctly. But I get use to putting headers in  Create Session keyword, and in that case, I must write an extra row to log my data value, or else difficult to debug.

Hope a more ideal solution.

### PR DESCRIPTION
**Pull request by qitaos**
data is not None, but log data is empty. Fix #155

### CODE REVIEW

**Comment by vkosuri** [comment]
@qitaos Thanks, the tests are failing

**Comment by qitaos** [comment]
@vkosuri fixed it.

**Comment by vkosuri** [comment]
sure

**Comment by vkosuri** [comment]
I am unable to checkout your pull request on machine. I will make another pull request. Is this OK?

**Comment by vkosuri** [comment]
I think this issue was addressed, If not please feel free reopen this issue. Fro time being I am closing this PR

**Pull request closed without merging**
