### PR TITLE
fix bug #128: post request works with arbitrary binary content

### PR DESCRIPTION
**Pull request by tarvohimanen**
Posting of octet-stream and other custom content-types are now supported by not logging them.
By not logging response content the decode(utf-8) is not made.

### CODE REVIEW

**Comment by bulkan** [comment]
Hi @tarvohimanen ,

Thanks for the PR. For some reason the tests are broken.

**Comment by bulkan** [comment]
@tarvohimanen cheers. The test for binary data is failing now

**Comment by tarvohimanen** [comment]
Noticed the build error and now fixed. Was my error not to run the full test stack before committing.

**Comment by bulkan** [comment]
@tarvohimanen all good. Thanks for fixing.

**Pull request merged**
