### PR TITLE
Mention in README that Requests library should be installed

### PR DESCRIPTION
**Pull request by pkuczynski**

### CODE REVIEW

**Comment by pkuczynski** [comment]
It's a bit of shame you ignored my suggestion to also list requirement to install requests library. This might be confusing for some not very advanced users...

**Comment by oleduc** [comment]
@pkuczynski This was included in PR #77

**Comment by bulkan** [comment]
Sorry @pkuczynski I should have written a comment when I closed this PR. There was a merge confilct and @vkosuri had already submitted another updated PR. Also I thought the inline update that #77 was merged would have been sufficient.

**Comment by pkuczynski** [comment]
My PR was only changing README after I stumbled upon the issue of missing dependencies, helping a friend to get going with Robot. My change was explicitly adding a line to install Request: 

Install robotframework-requests and it's dependencies via `pip`
  
```python
pip install -U requests
pip install -U robotframework-requests
```

Now the README says to install dependencies, but does not mention what they are. Thats why I feel it's still a bit confusing :(

**Comment by pkuczynski** [comment]
Ahh now I see you added this line too, so thats fine :) Hope that will make other people's life easier :)

**Pull request closed without merging**
