### PR TITLE
added documentation and examples for how to handle http proxies

### PR DESCRIPTION
**Pull request by jaloren**

### CODE REVIEW

**Comment by bulkan** [comment]
@jaloren the testcase you added is failing

**Comment by jaloren** [comment]
Can you show me the error?  I suspect its failing because the example  won't ever work in a normal network if this proxy doesn't exist.

http=http://acme.com:912  https=http://acme.com:913

Since proxies are obviously environmentally dependent, I can't ever put a real proxy. I could smoke this line though so it will pass even though it wouldn't be as realistic IMHO.

Should Be Equal As Integers  ${resp.status_code}  200

**Comment by bulkan** [comment]
@jaloren travis-ci is running the tests. See the output https://travis-ci.org/bulkan/robotframework-requests/jobs/50202962

**Comment by jaloren** [comment]
It should start passing now.

**Comment by bulkan** [comment]
Awesome thanks

**Comment by jaloren** [comment]
Hrrm...github is rendering of the table is jacked up. I literally cut and pasted the table from the top of the readme and put it below and then modified the values. I'll take a look.

**Comment by bulkan** [comment]
I've fixed it now. Cheers.

**Pull request merged**
