### PR TITLE
Check if data is blank before json.dumps

### LINKED ISSUE #259: ${EMPTY} is being treated as "" rather than a 'blank' past version 0.5.0
We have been having issues moving past version 0.5.0 due to some more verbose messaging that is happening after upgrading.

image

Any idea what triggers this additional logging and is there any way to suppress it? 

I noticed that in 0.6.2 you say that:
> response is logged if standard python/robotframework debug level is enabled (might be verbose)
Not sure if that is related but for us we are using the default log level of INFO.

Any assistance would be greatly appreciated, thanks.

### PR DESCRIPTION
**Pull request by Wolfe1**
Fixes #259

### CODE REVIEW

**Comment by Wolfe1** [comment]
Checking on that one failure

**Comment by lucagiove** [comment]
Sorry noticed right now the reference to the issue but still would be great to have more info.

**Comment by Wolfe1** [comment]
Just fixed the last test, forgot to cast it to a string before attempting the strip() check. 

I can reiterate the information on the issue but that seemed redundant.

**Comment by Wolfe1** [comment]
Will get you that test tomorrow.

**Comment by lucagiove** [comment]
Yes sorry I missed the other messages on the issue. Thank you very much for the analysis.
That is a tricky part I'll definitely have a look soon, now I'm abroad with limited access to a pc, but as soon as I've a bit of time I'll have a look. 

In the meantime if you've found why your case is peculiar, please reproduce it in a test that fails before your patch and include in the PR, that would help a lot me to understand the issue and prevent in the future to break your tests again 😁

**Comment by Wolfe1** [comment]
Alright since testing this requires us to actually see what is being sent to '_common_request' it wasn't really anything I could do in Robot Framework. This is really more of a job for a unit test so I went ahead and set it up.

image

The test mocks 'RequestsLibrary.RequestsLibrary._common_request' and then calls the api as normal. When we get to '_common_request' we can ask the mock what it was called with. In this case we only really care about data=''.

If you wish to test it failing you would just need to comment out line 1045 like so:
image

Where you would get this as an error:
image

**Comment by Wolfe1** [comment]
This is ran by travis-ci and will appear at the end of your report like so:
image
I included coverage information in it in case you ever want to [use something like coveralls to show your code coverage](https://coveralls.io/github/Accruent/robotframework-zoomba). Sadly this will not include your Robot tests in the coverage as line coverage cannot be detected this way (as far as I am aware).

**Pull request merged**
