### PR TITLE
add max_retries support

### PR DESCRIPTION
**Pull request by myzhan**
Occasionally, testcases are failed by network failure. If I need a retry to make it passed, I can pass max_retries=1 to Create Session.

### CODE REVIEW

**Comment by bulkan** [comment]
Thanks for this but I wont be able to merge it if tests are failing.

**Comment by myzhan** [comment]
I can't figure out why "Do Not Pretty Print a JSON object" is failing.

{u'key_two': u'this is a test string', u'key_one': u'true'} != {u'key_one': u'true', u'key_two': u'this is a test string'}

any idea?

**Comment by HelioGuilherme66** [comment]
Yes, try enclose them in ":
"{u'key_two': u'this is a test string', u'key_one': u'true'}" !=
"{u'key_one': u'true', u'key_two': u'this is a test string'}"

**Comment by myzhan** [comment]
This is the test.

Should Be Equal As Strings    ${jsondata['args']}    ${var}

Both ${jsondata['args']} and ${var} are dicts.

As a workaround, I can convert them to str, before passing them to robot's
build-in keyword, but it's not nice :(


2015-08-18 17:59 GMT+08:00 Hélio Guilherme <notifications@github.com>:

> Yes, try enclose them in ":
> "{u'key_two': u'this is a test string', u'key_one': u'true'}" !=
> "{u'key_one': u'true', u'key_two': u'this is a test string'}"
>

**Comment by HelioGuilherme66** [comment]
Now I see that the dictionaries are nor sorted. You must compare them using the same sort order. Do that before testing.

**Comment by bulkan** [comment]
@vkosuri I believe you're working on this right ? Can I close this PR ?

**Comment by vkosuri** [comment]
Yes

**Pull request closed without merging**
