### PR TITLE
Retry status all commits

### PR DESCRIPTION
**Pull request by lucagiove**
Merging again this PR (without squashing) should make more clear which PR are already integrated in this branch and automatically handle the still opened PR.

Let's check it out.

### CODE REVIEW

**Comment by lucagiove** [comment]
It seems fine, there is no actual diff but GitHub shows all the changes since commits are not detected as already merged.
So there are no actual changes from the other branch just the whole commit history will be preserved.

**Comment by asyrjasalo** [comment]
I think "This branch is out-of-date with the base branch" must be resolved first before GitHub allows us to merge (this time without squashing).

**Comment by lucagiove** [comment]
Done

Il mer 25 set 2019, 18:03 Anssi Syrjäsalo <notifications@github.com> ha
scritto:

**Comment by asyrjasalo** [comment]
This is good to go, as well as were the previous changes. Let me merge this without squashing now - if that is the way @lucagiove wants to roll. I hope Bulkan does not value ("master" git branch) history too much, due to overlapping changes with the previous PR - we will write a proper CHANGELOG.md on changes to compensate, if this is the case. 😉

@lucagiove: Consider releasing the new version to TestPyPI first, and msg this on the RF Slack channel. Let's have some feedback and checks before going to PyPI with a new release. There has been some time from the last release for this library in any case. The PyPI release is up to Mr. Evcimen in any case, but I think it's good to get this out.

**Comment by lucagiove** [comment]
Test PyPy: https://test.pypi.org/project/robotframework-requests/0.6.2/

**Comment by lucagiove** [comment]
Pasted on slack let's see what happens.

**Comment by bulkan** [comment]
@asyrjasalo 

> I hope Bulkan does not value ("master" git branch) history too much, due to overlapping changes with the previous PR

Actually I don't really mind at all.

> The PyPI release is up to Mr. Evcimen in any case, but I think it's good to get this out.

Just give me a heads up and I will publish a new release to PyPI.

**Pull request merged**
