### PR TITLE
Basic Python 3 compatibility.

### PR DESCRIPTION
**Pull request by tisto**
This pull requests adds basic Python 3 compatibility. It marks Python 3 tests as allowed failures on Travis. Though, this pull request can be merged right away because it does not break anything on Python 2. I saw that there are other pull requests already for Python 3 compatibility. Though, they are either incomplete or break Python 2.

### CODE REVIEW

**Comment by vkosuri** [comment]
@tisto Insted allow failures on , use specific one. https://improveandrepeat.com/2014/01/travis-ci-and-allowed-failures/

@bulkan I think it's better having two type of testcase for ``python 2.x`` and ``python 3.x``, it's give more converge.

**Comment by tisto** [comment]
@vkosuri the only build that is allowed to fail is Python 3.5. Am I missing something here?

**Comment by vkosuri** [comment]
@tisto oops, i just looked into last diff of 5886cc647aca236ea120f8ff786afc5e49fb5b3c

**Comment by tisto** [comment]
@vkosuri ok, cool. So I guess we are on the same page then. :)

**Comment by tisto** [comment]
@bulkan any chance you can have a look at that pull request and either merge it or tell me what's missing?

**Comment by bulkan** [comment]
@tisto my only concern is why we're not fixing tests so it passes when run with 3.5

**Comment by vkosuri** [comment]
The python3 PR has been merged into master, hence closing this issue https://github.com/bulkan/robotframework-requests/pull/130

**Comment by tisto** [comment]
@vkosuri thanks for the merge! Now we can continue to work on Python 3 compatibility. :)

**Comment by bulkan** [comment]
@vkosuri thanks for merging all these :) Let me know if I need to publish to PyPI with the latest RequestsLibrary

**Comment by vkosuri** [comment]
Sure

**Pull request closed without merging**
