### PR TITLE
Unicode payload tests

### PR DESCRIPTION
**Pull request by peterdemin**
Those tests check that Post Request handles unicode payload well.
Appropriate fixes will come in another PR after merge of #86 if needed.

### CODE REVIEW

**Comment by vkosuri** [comment]
@peterdemin @bulkan had merged changes into master could you try it again?

**Comment by peterdemin** [comment]
Failing test should be fixed in #97

**Comment by peterdemin** [comment]
Why don't you merge these tests?

**Comment by bulkan** [comment]
because tests are failing

**Comment by peterdemin** [comment]
They fail because code is broken. Not because tests contain error.

**Comment by vkosuri** [comment]
This failing from Post With Unicode Data testcase more information you can view by enabling debug flag

Root cause from here

``` json
{"two": 2, "one": 1, "non-ascii": "度假村"}
```

Debug information

<pre>
KEYWORD ${resp} = RequestsLibrary . Post Request httpbin, /post, data=${data}, headers=${headers}
Documentation: 	

Send a POST request on the session object found using the
Start / End / Elapsed: 	20160215 21:44:02.280 / 20160215 21:44:03.217 / 00:00:00.937
<b>21:44:02.280 	TRACE 	Arguments: [ 'httpbin' | '/post' | data=b'{"two": 2, "one": 1, "non-ascii": "\xe5\xba\xa6\xe5\x81\x87\xe6\x9d\x91"}' | headers={'Content-Type': 'application/x-www-form-urlencoded'} ] 	</b>
21:44:02.282 	INFO 	Starting new HTTP connection (1): httpbin.org 	
21:44:03.213 	DEBUG 	"POST /post HTTP/1.1" 200 492 	
21:44:03.214 	DEBUG 	send: POST /post HTTP/1.1
Host: httpbin.org
Content-Length: 46
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.7.0 CPython/2.7.10 Windows/7
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded
<b>{"two": 2, "one": 1, "non-ascii": "\xe5\xba\xa6\xe5\x81\x87\xe6\x9d\x91"}</b>
reply: HTTP/1.1 200 OK
header: Server: nginx
header: Date: Mon, 15 Feb 2016 16:13:57 GMT
header: Content-Type: application/json
header: Content-Length: 492
header: Connection: keep-alive
header: Access-Control-Allow-Origin: *
header: Access-Control-Allow-Credentials: true 	
21:44:03.215 	DEBUG 	post response: {
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {
   <b> "{\"two\": 2, \"one\": 1, \"non-ascii\": \"\u5ea6\u5047\u6751\"}": ""</b>
  }, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate", 
    "Content-Length": "46", 
    "Content-Type": "application/x-www-form-urlencoded", 
    "Host": "httpbin.org", 
    "User-Agent": "python-requests/2.7.0 CPython/2.7.10 Windows/7"
  }, 
  "json": null, 
  "origin": "103.194.132.167", 
  "url": "http://httpbin.org/post"
}
	
21:44:03.216 	FAIL 	UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 35: ordinal not in range(128)
</pre>

**Comment by oleduc** [comment]
@vkosuri I think @peterdemin  is saying that his subsequent pull request fixes this issue.

@peterdemin Do you think you could close this pull request and add the test to the same PR that this is trying to test?

**Comment by bulkan** [comment]
I tried merging this branch & #89 into another with the latest changes from but the tests still fail

**Comment by peterdemin** [comment]
I reapplied fix in #99 and checked, that these tests pass on top.

**Comment by peterdemin** [comment]
Also, I merged these tests directly onto #99 to remove confusion

**Pull request closed without merging**
