### PR TITLE
Fix issue with CA_BUNDLE not working with Create Session verify

### PR DESCRIPTION
**Pull request by tguevin**
Fixes https://github.com/bulkan/robotframework-requests/issues/152

### CODE REVIEW

**Comment by vkosuri** [comment]
@tguevin I think it should like this, still needs to add another else condition for other than ``str`` or ``unicode``

```Python
# verify can be a Boolean or a String
        if isinstance(verify, bool):
            s.verify = verify
        elif isinstance(verify, str) or isinstance(verify, unicode):
            if verify.lower() == 'true' or verify.lower() == 'false':
                s.verify = self.builtin.convert_to_boolean(verify)
            else:
                # not a Boolean nor a String
                s.verify = verify
        else:
            s.verify = verify
```

**Comment by tguevin** [comment]
Thanks @vkosuri , please see update.

**Comment by vkosuri** [comment]
@tguevin Thanks, Cheer 👍

**Comment by tguevin** [comment]
Thanks, @vkosuri , do you know if a new version (like 0.4.7) will be built and released with this fix?

**Comment by vkosuri** [comment]
@bulkan could please make a release?

**Comment by tguevin** [comment]
Hi @bulkan , we have a demo on Thursday and would love to be able to use 0.4.7 version of this.  Is there anything we can do to help move this ahead?

**Comment by vkosuri** [comment]
@tguevin thanks for your patience, now everything is in master, @bulkan could make a pypi release 0.4.7? and also could you maintainer for ``pypi``?

**Comment by vkosuri** [comment]
@bulkan any further updates?

**Comment by tguevin** [comment]
Hi, @vkosuri  and @bulkan  is there any update on a new release?  We are hoping to get this so we can incorporate our new Robot certificate tests into our mainline code.  Thanks.

**Comment by bulkan** [comment]
pushed v0.4.7 to PyPI

**Comment by vkosuri** [comment]
@bulkan Thank you very much.

**Comment by bulkan** [comment]
@vkosuri this test is failing now https://travis-ci.org/bulkan/robotframework-requests/jobs/215349742

**Comment by tguevin** [comment]
In my testing, I have had to add "SAN" names to my certificate. To do this, I added "-reqexts SAN" to the openssl req, and specified the SAN as subjectAltName=DNS:_____ in openssl.conf.  Did the same when creating the CA:
    -extensions SAN \
    -extfile <(cat certificates/intermediate/openssl.cnf  \
        <(printf "[SAN]\nsubjectAltName=DNS:${IP}")) \

Btw, I tested with the new version 0.4.7 and it works perfectly with my tests.  Thank you @bulkan and @vkosuri

**Comment by vkosuri** [comment]
@bulkan Looking into the issue in my machine.

**Comment by vkosuri** [comment]
Surprisingly the test are failing with ``0.4.6`` version also on Python ``2.6`` and Python ``2.7`` versions only. It was fine with other ``Python3`` version. The error message which i am getting is

```Bash
Get HTTPS & Verify Cert with a CA bundle                              | FAIL |
SSLError: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```` 

Digging more into this issue.

**Comment by vkosuri** [comment]
Some more info https://github.com/kennethreitz/requests/issues/321

@kennethreitz comments are 

> Sorry, httpbin's cert is a little bit messed up. Depends on the ssl version.

**Comment by vkosuri** [comment]
I am going to make these changes on .travis.yml

``` Bash
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 -o $TRAVIS_PYTHON_VERSION == 2.7]]; then pybot --noncritical get-cert -P src tests; fi
  - pybot -P src tests
```

@bulkan any comments/suggestions?

**Pull request merged**
